# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poc_swagger3_security?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      data-locations: classpath*:data.sql

server:
  port: 8080

global-logistic:
  openapi:
    url: http://localhost:8080
    description: Server URL in Production Environment
