DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS roles (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(250) NOT NULL
);

INSERT INTO roles
(name)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER'),
       ('ROLE_MODERATOR');