# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:poc_swagger3_security;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath*:data.sql


server:
  port: 8082 # no cambiar en prod

global-logistic:
  openapi:
    url: http://localhost:8082
    description: Server URL in Staging Environment


